### ISSUE TITLE
CORS error!!! kindly solve. 

### ISSUE THREAD

**Issue by yashmks1998** [witerahq/witerahq.github.io#3]
![Capture](https://user-images.githubusercontent.com/39986456/88061667-70190c00-cb85-11ea-9f98-8a5bd7d97b87.PNG)\
@naseemali925

**Comment by inaseem** [comment]
I will look into this @yashmks1998 asap.

**Comment by iamshouvikmitra** [comment]
Seems like the entries are happening in the Google Sheet despite the error

**Comment by inaseem** [comment]
> Seems like the entries are happening in the Google Sheet despite the error

Yeah, that is strange. I am making some changes. Lets see if that resolved it.

**Comment by inaseem** [comment]
Fixed :tada: :tada:
